[package]
name = "archivar"
version = "0.1.0"
authors = ["Yannik Sander <me@ysndr.de>"]

[dependencies]
cargo = "0.26.0"
clap = "2.26.0"
slog = { version = "2.2.3",  features = ["max_level_trace"] }
slog-term = "2.3.0"
slog-async = "2.3.0"
sloggers = "0.2.6"
error-chain = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
